// Copyright 2022 Convai Inc. All Rights Reserved.

#include "Gaze/ConvaiGazeHighlightActor.h"

#include "Components/MeshComponent.h"
#include "Components/SceneComponent.h"
#include "DrawDebugHelpers.h"
#include "Engine/World.h"
#include "GameFramework/Actor.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "Runtime/Launch/Resources/Version.h"
#include "UObject/ConstructorHelpers.h"

namespace
{
	// Plugin-shipped Fresnel-rim silhouette material. Has EmissiveColor (Vector), EmissiveIntensity
	// (Scalar), EdgeFalloff (Scalar), EdgeOpacity (Scalar). Generated by
	// Convai/Content/Tools/CreateGazeOverlayMaterial.py so the graph is reproducible.
	const TCHAR* GDefaultOverlayMaterialPath =
		TEXT("/ConvAI/Highlights/M_ConvaiGazeOverlay.M_ConvaiGazeOverlay");

	// Engine fallback used only if the plugin asset is missing (e.g. cooked build that stripped
	// plugin Content). EmissiveMeshMaterial is hardcoded white — no parameters — so tint won't
	// apply, but the user still sees *something* highlighted instead of a silent failure.
	const TCHAR* GFallbackOverlayMaterialPath =
		TEXT("/Engine/EngineMaterials/EmissiveMeshMaterial.EmissiveMeshMaterial");
}

AConvaiGazeHighlightActor::AConvaiGazeHighlightActor()
{
#if ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 3)
	// Overlay material stamps onto the mesh and tracks animation automatically — no tick needed.
	PrimaryActorTick.bCanEverTick = false;
	PrimaryActorTick.bStartWithTickEnabled = false;
#else
	// 5.0-5.2 fallback redraws the debug box every frame because DrawDebugBox isn't persistent.
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bStartWithTickEnabled = true;
#endif

	// AttachToActor needs a RootComponent on the source actor; without one it logs an error
	// and silently fails to attach. Give us a trivial SceneComponent root so the attach
	// succeeds cleanly even though we don't draw via our own transform.
	USceneComponent* Root = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
	SetRootComponent(Root);

	bReplicates = false;
	SetCanBeDamaged(false);

	// ConstructorHelpers::FObjectFinder runs at class CDO construction — safe place to grab the
	// plugin material so we don't pay a LoadObject hit per SetTarget call at runtime. Fall
	// through to the engine material if the plugin asset is missing.
	static ConstructorHelpers::FObjectFinder<UMaterialInterface> PluginMatFinder(GDefaultOverlayMaterialPath);
	if (PluginMatFinder.Succeeded())
	{
		OverlayMaterial = PluginMatFinder.Object;
	}
	else
	{
		static ConstructorHelpers::FObjectFinder<UMaterialInterface> EngineMatFinder(GFallbackOverlayMaterialPath);
		if (EngineMatFinder.Succeeded())
		{
			OverlayMaterial = EngineMatFinder.Object;
		}
	}
}

void AConvaiGazeHighlightActor::SetTarget(AActor* InTarget, USceneComponent* InTargetComponent)
{
	SetTargets(InTarget ? TArray<AActor*>{ InTarget } : TArray<AActor*>{}, InTargetComponent);
}

void AConvaiGazeHighlightActor::SetTargets(const TArray<AActor*>& InTargets, USceneComponent* InTargetComponent)
{
	AActor* NewPrimary = nullptr;
	for (AActor* A : InTargets)
	{
		if (IsValid(A)) { NewPrimary = A; break; }
	}

	// No-op guard: same primary + same component scope + identical target SET. (Gaze only
	// re-spawns highlights on target transitions, so this is rarely hit — but compare the
	// actual set, not just the count, so [A,B] -> [A,C] is not mistaken for unchanged.)
	if (NewPrimary == Target.Get() && InTargetComponent == TargetComponent.Get())
	{
		bool bSameSet = true;
		for (const TWeakObjectPtr<AActor>& Cur : Targets)
		{
			if (!InTargets.Contains(Cur.Get())) { bSameSet = false; break; }
		}
		if (bSameSet)
		{
			for (AActor* A : InTargets)
			{
				if (IsValid(A) && !Targets.Contains(A)) { bSameSet = false; break; }
			}
		}
		if (bSameSet) { return; }
	}

	// Unbind from all previous targets before swapping.
	UnbindTargets();

	ClearOverlay();
	Targets.Reset();
	Target = NewPrimary;
	TargetComponent = InTargetComponent;

	if (!NewPrimary)
	{
		return;
	}

	for (AActor* A : InTargets)
	{
		if (!IsValid(A) || Targets.Contains(A)) { continue; }
		Targets.Add(A);
		// Self-destruct if ANY target is destroyed while we're attached — on UE 5.3+ tick
		// is off, so without this binding we'd stay alive forever after a destroyed-during-gaze.
		A->OnDestroyed.AddDynamic(this, &AConvaiGazeHighlightActor::HandleTargetDestroyed);
	}

	AttachToActor(NewPrimary, FAttachmentTransformRules::KeepWorldTransform);
	ApplyOverlay();
}

void AConvaiGazeHighlightActor::HandleTargetDestroyed(AActor* DestroyedActor)
{
	// ClearOverlay's IsValid checks skip any pending-kill mesh components, so this is safe
	// even though the destroyed target's components may already be tearing down.
	ClearOverlay();

	if (DestroyedActor)
	{
		DestroyedActor->OnDestroyed.RemoveDynamic(this, &AConvaiGazeHighlightActor::HandleTargetDestroyed);
	}
	// Drop the destroyed member (and any now-stale weak refs).
	Targets.RemoveAll([DestroyedActor](const TWeakObjectPtr<AActor>& T)
	{
		return !T.IsValid() || T.Get() == DestroyedActor;
	});

	// If members of a merged set survive, re-home onto one and repaint so the collective
	// highlight stays up — the gaze tick won't re-spawn while the player keeps gazing the
	// same object. Otherwise there's nothing left to show, so self-destruct.
	AActor* NewPrimary = Targets.Num() > 0 ? Targets[0].Get() : nullptr;
	if (!NewPrimary)
	{
		Target.Reset();
		Destroy();
		return;
	}
	Target = NewPrimary;
	AttachToActor(NewPrimary, FAttachmentTransformRules::KeepWorldTransform);
	ApplyOverlay();
}

void AConvaiGazeHighlightActor::UnbindTargets()
{
	for (const TWeakObjectPtr<AActor>& Tw : Targets)
	{
		if (AActor* TA = Tw.Get())
		{
			TA->OnDestroyed.RemoveDynamic(this, &AConvaiGazeHighlightActor::HandleTargetDestroyed);
		}
	}
}

void AConvaiGazeHighlightActor::ApplyOverlay()
{
#if ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 3)
	AActor* T = Target.Get();
	if (!T)
	{
		return;
	}

	UMaterialInterface* Base = OverlayMaterial.LoadSynchronous();
	if (!Base)
	{
		// Engine material missing in cooked build? Tick fallback to DrawDebugBox will be a no-op
		// since we disabled tick above; this is intentionally silent — projects can supply their
		// own OverlayMaterial via UConvaiPlayerComponent if engine content was stripped.
		return;
	}

	OverlayMID = UMaterialInstanceDynamic::Create(Base, this);
	if (!OverlayMID)
	{
		return;
	}
	// Drive the plugin material's params. Pass HighlightColor un-scaled to EmissiveColor and
	// let the material multiply by EmissiveIntensity internally — preserves the parameter
	// semantics so projects that subclass the material via a Material Instance can drive both
	// independently. SetVectorParameterValue is a silent no-op on materials that don't expose
	// the parameter, so we also write the common alternate name "Color" for foreign overlay
	// materials a project might swap in.
	OverlayMID->SetVectorParameterValue(TEXT("EmissiveColor"), HighlightColor);
	OverlayMID->SetVectorParameterValue(TEXT("Color"), HighlightColor);
	OverlayMID->SetScalarParameterValue(TEXT("EmissiveIntensity"), EmissiveIntensity);

	TArray<UMeshComponent*> Meshes;
	if (USceneComponent* Scope = TargetComponent.Get())
	{
		// Component-scoped highlight. Two cases:
		//   - Scope IS a mesh component (most common — ComponentName resolved to a specific
		//     mesh): paint ONLY that mesh. Don't descend, otherwise attached sub-meshes
		//     (e.g. weapons / hats parented to a character's skeletal mesh) get painted too
		//     and the silhouette visually bleeds across the actor.
		//   - Scope is a non-mesh USceneComponent (e.g. an organizational parent that groups
		//     mesh children): descend to find every mesh descendant so the overlay is
		//     actually visible somewhere.
		if (UMeshComponent* ScopeMesh = Cast<UMeshComponent>(Scope))
		{
			Meshes.Add(ScopeMesh);
		}
		else
		{
			TArray<USceneComponent*> ScopeChildren;
			Scope->GetChildrenComponents(/*bIncludeAllDescendants=*/ true, ScopeChildren);
			for (USceneComponent* C : ScopeChildren)
			{
				if (UMeshComponent* CM = Cast<UMeshComponent>(C))
				{
					Meshes.AddUnique(CM);
				}
			}
		}
	}
	else
	{
		// Whole-actor scope: paint every mesh on every target actor so a merged set of
		// same-named objects highlights collectively. (For a normal highlight, Targets is
		// just { Target }.)
		for (const TWeakObjectPtr<AActor>& Tw : Targets)
		{
			if (AActor* TA = Tw.Get())
			{
				TArray<UMeshComponent*> ActorMeshes;
				TA->GetComponents<UMeshComponent>(ActorMeshes, /*bIncludeFromChildActors=*/ true);
				// AddUnique: a mesh shared across two targets (e.g. via child actors) must
				// not be recorded twice, or ClearOverlay could restore our MID as its "prior".
				for (UMeshComponent* MC : ActorMeshes) { Meshes.AddUnique(MC); }
			}
		}
	}
	AffectedMeshComponents.Reserve(Meshes.Num());
	PriorOverlayMaterials.Reserve(Meshes.Num());

	for (UMeshComponent* MC : Meshes)
	{
		if (!IsValid(MC))
		{
			continue;
		}
		PriorOverlayMaterials.Add(MC->GetOverlayMaterial());
		AffectedMeshComponents.Add(MC);
		MC->SetOverlayMaterial(OverlayMID);
	}
#endif
}

void AConvaiGazeHighlightActor::ClearOverlay()
{
#if ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 3)
	const int32 Num = AffectedMeshComponents.Num();
	for (int32 i = 0; i < Num; ++i)
	{
		// IsValid check guards the destroyed-target path: target actor (and its mesh
		// components) may already be pending-kill by the time we get here, calling
		// SetOverlayMaterial on those would crash or warn.
		UMeshComponent* MC = AffectedMeshComponents[i];
		if (IsValid(MC))
		{
			UMaterialInterface* Prior = PriorOverlayMaterials.IsValidIndex(i) ? PriorOverlayMaterials[i] : nullptr;
			MC->SetOverlayMaterial(Prior);
		}
	}
#endif
	AffectedMeshComponents.Reset();
	PriorOverlayMaterials.Reset();
	OverlayMID = nullptr;
}

void AConvaiGazeHighlightActor::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	UnbindTargets();
	ClearOverlay();
	Super::EndPlay(EndPlayReason);
}

void AConvaiGazeHighlightActor::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

#if !(ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 3))
	// 5.0-5.2 fallback: SetOverlayMaterial on UMeshComponent isn't available, so re-emit a debug
	// wireframe box every frame. Single tick path used only in these old versions.
	AActor* T = Target.Get();
	if (!T)
	{
		Destroy();
		return;
	}

	FVector Origin = FVector::ZeroVector;
	FVector Extent = FVector::ZeroVector;
	T->GetActorBounds(/*bOnlyCollidingComponents=*/ false, Origin, Extent, /*bIncludeFromChildActors=*/ true);
	if (Extent.IsNearlyZero())
	{
		return;
	}
	if (UWorld* World = GetWorld())
	{
		DrawDebugBox(World,
			Origin,
			Extent * FallbackBoxPadding,
			HighlightColor.ToFColor(true),
			/*bPersistent=*/ false,
			/*LifeTime=*/ -1.0f,
			/*DepthPriority=*/ 0,
			FallbackBoxThickness);
	}
#endif
}
