// Copyright 2022 Convai Inc. All Rights Reserved.

#include "Gaze/ConvaiGazeHighlightActor.h"

#include "Components/MeshComponent.h"
#include "Components/SceneComponent.h"
#include "DrawDebugHelpers.h"
#include "Engine/World.h"
#include "GameFramework/Actor.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "Runtime/Launch/Resources/Version.h"
#include "UObject/ConstructorHelpers.h"

namespace
{
	// Plugin-shipped Fresnel-rim silhouette material. Has EmissiveColor (Vector), EmissiveIntensity
	// (Scalar), EdgeFalloff (Scalar), EdgeOpacity (Scalar). Generated by
	// Convai/Content/Tools/CreateGazeOverlayMaterial.py so the graph is reproducible.
	const TCHAR* GDefaultOverlayMaterialPath =
		TEXT("/ConvAI/Highlights/M_ConvaiGazeOverlay.M_ConvaiGazeOverlay");

	// Engine fallback used only if the plugin asset is missing (e.g. cooked build that stripped
	// plugin Content). EmissiveMeshMaterial is hardcoded white — no parameters — so tint won't
	// apply, but the user still sees *something* highlighted instead of a silent failure.
	const TCHAR* GFallbackOverlayMaterialPath =
		TEXT("/Engine/EngineMaterials/EmissiveMeshMaterial.EmissiveMeshMaterial");
}

AConvaiGazeHighlightActor::AConvaiGazeHighlightActor()
{
#if ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 3)
	// Overlay material stamps onto the mesh and tracks animation automatically — no tick needed.
	PrimaryActorTick.bCanEverTick = false;
	PrimaryActorTick.bStartWithTickEnabled = false;
#else
	// 5.0-5.2 fallback redraws the debug box every frame because DrawDebugBox isn't persistent.
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bStartWithTickEnabled = true;
#endif

	// AttachToActor needs a RootComponent on the source actor; without one it logs an error
	// and silently fails to attach. Give us a trivial SceneComponent root so the attach
	// succeeds cleanly even though we don't draw via our own transform.
	USceneComponent* Root = CreateDefaultSubobject<USceneComponent>(TEXT("Root"));
	SetRootComponent(Root);

	bReplicates = false;
	SetCanBeDamaged(false);

	// ConstructorHelpers::FObjectFinder runs at class CDO construction — safe place to grab the
	// plugin material so we don't pay a LoadObject hit per SetTarget call at runtime. Fall
	// through to the engine material if the plugin asset is missing.
	static ConstructorHelpers::FObjectFinder<UMaterialInterface> PluginMatFinder(GDefaultOverlayMaterialPath);
	if (PluginMatFinder.Succeeded())
	{
		OverlayMaterial = PluginMatFinder.Object;
	}
	else
	{
		static ConstructorHelpers::FObjectFinder<UMaterialInterface> EngineMatFinder(GFallbackOverlayMaterialPath);
		if (EngineMatFinder.Succeeded())
		{
			OverlayMaterial = EngineMatFinder.Object;
		}
	}
}

void AConvaiGazeHighlightActor::SetTarget(AActor* InTarget, USceneComponent* InTargetComponent)
{
	if (InTarget == Target.Get() && InTargetComponent == TargetComponent.Get())
	{
		return;
	}

	// Unbind from the previous target, if we had one, before swapping.
	if (AActor* Prev = Target.Get())
	{
		Prev->OnDestroyed.RemoveDynamic(this, &AConvaiGazeHighlightActor::HandleTargetDestroyed);
	}

	ClearOverlay();
	Target = InTarget;
	TargetComponent = InTargetComponent;

	if (!InTarget)
	{
		return;
	}

	// Self-destruct if the target is destroyed while we're attached — on UE 5.3+ tick is off
	// so without this binding we'd stay alive forever after a destroyed-during-gaze.
	InTarget->OnDestroyed.AddDynamic(this, &AConvaiGazeHighlightActor::HandleTargetDestroyed);

	AttachToActor(InTarget, FAttachmentTransformRules::KeepWorldTransform);
	ApplyOverlay();
}

void AConvaiGazeHighlightActor::HandleTargetDestroyed(AActor* /*DestroyedActor*/)
{
	// ClearOverlay's IsValid checks will skip any pending-kill mesh components, so this is
	// safe to call even though Target's components may already be tearing down.
	ClearOverlay();
	Target.Reset();
	Destroy();
}

void AConvaiGazeHighlightActor::ApplyOverlay()
{
#if ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 3)
	AActor* T = Target.Get();
	if (!T)
	{
		return;
	}

	UMaterialInterface* Base = OverlayMaterial.LoadSynchronous();
	if (!Base)
	{
		// Engine material missing in cooked build? Tick fallback to DrawDebugBox will be a no-op
		// since we disabled tick above; this is intentionally silent — projects can supply their
		// own OverlayMaterial via UConvaiPlayerComponent if engine content was stripped.
		return;
	}

	OverlayMID = UMaterialInstanceDynamic::Create(Base, this);
	if (!OverlayMID)
	{
		return;
	}
	// Drive the plugin material's params. Pass HighlightColor un-scaled to EmissiveColor and
	// let the material multiply by EmissiveIntensity internally — preserves the parameter
	// semantics so projects that subclass the material via a Material Instance can drive both
	// independently. SetVectorParameterValue is a silent no-op on materials that don't expose
	// the parameter, so we also write the common alternate name "Color" for foreign overlay
	// materials a project might swap in.
	OverlayMID->SetVectorParameterValue(TEXT("EmissiveColor"), HighlightColor);
	OverlayMID->SetVectorParameterValue(TEXT("Color"), HighlightColor);
	OverlayMID->SetScalarParameterValue(TEXT("EmissiveIntensity"), EmissiveIntensity);

	TArray<UMeshComponent*> Meshes;
	if (USceneComponent* Scope = TargetComponent.Get())
	{
		// Component-scoped highlight. Two cases:
		//   - Scope IS a mesh component (most common — ComponentName resolved to a specific
		//     mesh): paint ONLY that mesh. Don't descend, otherwise attached sub-meshes
		//     (e.g. weapons / hats parented to a character's skeletal mesh) get painted too
		//     and the silhouette visually bleeds across the actor.
		//   - Scope is a non-mesh USceneComponent (e.g. an organizational parent that groups
		//     mesh children): descend to find every mesh descendant so the overlay is
		//     actually visible somewhere.
		if (UMeshComponent* ScopeMesh = Cast<UMeshComponent>(Scope))
		{
			Meshes.Add(ScopeMesh);
		}
		else
		{
			TArray<USceneComponent*> ScopeChildren;
			Scope->GetChildrenComponents(/*bIncludeAllDescendants=*/ true, ScopeChildren);
			for (USceneComponent* C : ScopeChildren)
			{
				if (UMeshComponent* CM = Cast<UMeshComponent>(C))
				{
					Meshes.AddUnique(CM);
				}
			}
		}
	}
	else
	{
		T->GetComponents<UMeshComponent>(Meshes, /*bIncludeFromChildActors=*/ true);
	}
	AffectedMeshComponents.Reserve(Meshes.Num());
	PriorOverlayMaterials.Reserve(Meshes.Num());

	for (UMeshComponent* MC : Meshes)
	{
		if (!IsValid(MC))
		{
			continue;
		}
		PriorOverlayMaterials.Add(MC->GetOverlayMaterial());
		AffectedMeshComponents.Add(MC);
		MC->SetOverlayMaterial(OverlayMID);
	}
#endif
}

void AConvaiGazeHighlightActor::ClearOverlay()
{
#if ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 3)
	const int32 Num = AffectedMeshComponents.Num();
	for (int32 i = 0; i < Num; ++i)
	{
		// IsValid check guards the destroyed-target path: target actor (and its mesh
		// components) may already be pending-kill by the time we get here, calling
		// SetOverlayMaterial on those would crash or warn.
		UMeshComponent* MC = AffectedMeshComponents[i];
		if (IsValid(MC))
		{
			UMaterialInterface* Prior = PriorOverlayMaterials.IsValidIndex(i) ? PriorOverlayMaterials[i] : nullptr;
			MC->SetOverlayMaterial(Prior);
		}
	}
#endif
	AffectedMeshComponents.Reset();
	PriorOverlayMaterials.Reset();
	OverlayMID = nullptr;
}

void AConvaiGazeHighlightActor::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	ClearOverlay();
	Super::EndPlay(EndPlayReason);
}

void AConvaiGazeHighlightActor::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

#if !(ENGINE_MAJOR_VERSION > 5 || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 3))
	// 5.0-5.2 fallback: SetOverlayMaterial on UMeshComponent isn't available, so re-emit a debug
	// wireframe box every frame. Single tick path used only in these old versions.
	AActor* T = Target.Get();
	if (!T)
	{
		Destroy();
		return;
	}

	FVector Origin = FVector::ZeroVector;
	FVector Extent = FVector::ZeroVector;
	T->GetActorBounds(/*bOnlyCollidingComponents=*/ false, Origin, Extent, /*bIncludeFromChildActors=*/ true);
	if (Extent.IsNearlyZero())
	{
		return;
	}
	if (UWorld* World = GetWorld())
	{
		DrawDebugBox(World,
			Origin,
			Extent * FallbackBoxPadding,
			HighlightColor.ToFColor(true),
			/*bPersistent=*/ false,
			/*LifeTime=*/ -1.0f,
			/*DepthPriority=*/ 0,
			FallbackBoxThickness);
	}
#endif
}
