// Copyright 2022 Convai Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "ConvaiGazeHighlightActor.generated.h"

class UMaterialInterface;
class UMaterialInstanceDynamic;
class UMeshComponent;

/**
 * Lightweight visual marker that ConvaiPlayerComponent spawns over whatever
 * Convai-object actor the player is currently looking at.
 *
 * UE 5.3+: paints a tinted emissive overlay on every UMeshComponent of the target via
 * UMeshComponent::SetOverlayMaterial. Default material is the plugin-shipped
 * /ConvAI/Highlights/M_ConvaiGazeOverlay (Fresnel rim silhouette, generated by
 * Content/Tools/CreateGazeOverlayMaterial.py). Falls back to
 * /Engine/EngineMaterials/EmissiveMeshMaterial only if the plugin asset was stripped
 * from a cooked build — note that material has no parameters so the fallback won't honor
 * HighlightColor / EmissiveIntensity. Projects can swap in any UMaterialInterface that
 * exposes an "EmissiveColor" vector parameter via UConvaiPlayerComponent.
 *
 * UE 5.0-5.2: SetOverlayMaterial on UMeshComponent doesn't exist there, so we fall
 * back to DrawDebugBox over the target's bounds.
 *
 * Subclass this actor and assign the subclass to UConvaiPlayerComponent::GazeHighlightActorClass
 * for fully custom visuals.
 */
UCLASS(Blueprintable, BlueprintType, ClassGroup = (Convai), HideCategories = (Input, Rendering, Replication, Collision, LOD, Cooking))
class CONVAI_API AConvaiGazeHighlightActor : public AActor
{
	GENERATED_BODY()

public:
	AConvaiGazeHighlightActor();

	virtual void Tick(float DeltaSeconds) override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

	/**
	 * Apply the highlight to InTarget. Pass nullptr to clear. Safe to call multiple times.
	 * When InTargetComponent is non-null AND castable to a UMeshComponent, the overlay material
	 * is only stamped on that specific mesh component instead of every UMeshComponent on the
	 * actor — used by the player when a UConvaiObjectComponent has a ComponentName filter so
	 * the silhouette tracks just the targeted sub-component (e.g. a door's "Handle").
	 */
	UFUNCTION(BlueprintCallable, Category = "Convai|Gaze")
	void SetTarget(AActor* InTarget, USceneComponent* InTargetComponent = nullptr);

	/**
	 * Apply the highlight collectively to several actors at once — used for a merged set
	 * of same-named Convai objects so gazing at one lights up all of them. The first
	 * valid actor is the primary (attachment + the 5.0-5.2 fallback box); the overlay is
	 * painted on every actor's meshes. Component scope only makes sense for a single
	 * actor, so InTargetComponent is honored only when one actor is passed.
	 */
	UFUNCTION(BlueprintCallable, Category = "Convai|Gaze")
	void SetTargets(const TArray<AActor*>& InTargets, USceneComponent* InTargetComponent = nullptr);

	/** Read-only access to the current target, for BP subclasses that want to layer extra visuals. */
	UFUNCTION(BlueprintPure, Category = "Convai|Gaze")
	AActor* GetTarget() const { return Target.Get(); }

	/** Optional sub-component scope set by SetTarget. Null when the highlight covers the whole actor. */
	UFUNCTION(BlueprintPure, Category = "Convai|Gaze")
	USceneComponent* GetTargetComponent() const { return TargetComponent.Get(); }

	/**
	 * Tint applied to the overlay material's EmissiveColor parameter. The player component
	 * forwards UConvaiPlayerComponent::GazeHighlightColor into this before SetTarget.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Convai|Gaze")
	FLinearColor HighlightColor = FLinearColor(1.0f, 0.9f, 0.2f, 1.0f);

	/** Scalar multiplier on HighlightColor before it goes into the EmissiveColor parameter. Brightness knob. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Convai|Gaze", meta = (ClampMin = "0.0"))
	float EmissiveIntensity = 2.5f;

	/**
	 * Material used as the overlay tint. Defaults to /Engine/EngineMaterials/EmissiveMeshMaterial
	 * which exposes an EmissiveColor vector parameter that we drive from HighlightColor. Override
	 * with any UMaterialInterface that exposes an "EmissiveColor" vector parameter.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Convai|Gaze")
	TSoftObjectPtr<UMaterialInterface> OverlayMaterial;

	/** Line thickness for the fallback wireframe box (UE 5.0-5.2 only, where SetOverlayMaterial isn't available). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Convai|Gaze", AdvancedDisplay)
	float FallbackBoxThickness = 2.0f;

	/** Multiplier on bounds extent for the fallback box (5.0-5.2 only). */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Convai|Gaze", AdvancedDisplay, meta = (ClampMin = "1.0"))
	float FallbackBoxPadding = 1.05f;

protected:
	UFUNCTION()
	void HandleTargetDestroyed(AActor* DestroyedActor);

	UPROPERTY(Transient)
	TWeakObjectPtr<AActor> Target;

	/**
	 * Every actor the overlay is painted on. For a normal highlight this is just
	 * { Target }; for a merged set it is all the member actors. Target is Targets[0].
	 */
	UPROPERTY(Transient)
	TArray<TWeakObjectPtr<AActor>> Targets;

	/** Optional component scope; when set, the overlay is restricted to this single component. */
	UPROPERTY(Transient)
	TWeakObjectPtr<USceneComponent> TargetComponent;

	/**
	 * Mesh components whose overlay material we replaced — parallel to PriorOverlayMaterials.
	 * UPROPERTY so GC tracks them while the highlight is alive.
	 */
	UPROPERTY(Transient)
	TArray<UMeshComponent*> AffectedMeshComponents;

	/** Original overlay materials we displaced, restored 1:1 on SetTarget(nullptr) / EndPlay. */
	UPROPERTY(Transient)
	TArray<UMaterialInterface*> PriorOverlayMaterials;

	/** The MID we created to drive the EmissiveColor parameter. Lives as long as the highlight does. */
	UPROPERTY(Transient)
	UMaterialInstanceDynamic* OverlayMID = nullptr;

	void ApplyOverlay();
	void ClearOverlay();

	/** Remove our HandleTargetDestroyed binding from every actor in Targets. */
	void UnbindTargets();
};
